### ISSUE TITLE
implement entity parsing

### ISSUE THREAD

**Issue by NickSavage** [NickSavage/Zettelgarden#31]

**Comment by NickSavage** [comment]
this is done

**Comment by t1u1** [comment]
You may want to also ask the LLM whether an entity is defined by the card or merely referenced. That would enable you to implement:
> A particularly intriguing possibility is using the entity system to help identify gaps in knowledge. If multiple cards reference a specific concept or person, but there's no dedicated card exploring that entity in depth, that might be a valuable signal for where to focus future research and note-taking.
